# Server properties
server:
  servlet:
    context-path: /ssmu-api
  port: 8080
# Spring properties
spring:
  # Dev is active by default. This value can be overwritten by java arg param
  profiles:
    active: dev
  application:
    name: ssmu-api
